---
version: "3.6"

volumes:
  db-data:
  redis-data:

networks:
  default:
    driver: bridge

services:
  web-php:
    env_file: .env
    restart: unless-stopped
    container_name: ${PROJECT}-web
    image: "bbdrummer/my-application-runtime-php:8-1"
    ports:
      - "${WEBPORT}:8080"
    volumes:
        - ./:/var/www
        #- ${SRC_PATH}/public/:/var/www/html
    links:
      - svc_db_mysql
      - svc_redis

  admin-pma:
    env_file: .env
    restart: unless-stopped
    container_name: ${PROJECT}-admin-pma
    image: "phpmyadmin/phpmyadmin"
    environment:
      PMA_HOST: my-application-mysql
    ports:
      - "${PMAPORT}:80"
    links:
      - svc_db_mysql

  svc_db_mysql:
    env_file: .env
    restart: unless-stopped
    container_name: ${PROJECT}-mysql
    #image: "bbdrummer/mysql-runtime-env:latest"
    image: "mariadb:10.6"
    #command: 'mysqld --authentication_policy=mysql_native_password --user=root'
    command:
      - --default-authentication-plugin=mysql_native_password
      - --collation-server=utf8mb4_unicode_ci
      - --character-set-server=utf8mb4
      - --innodb_buffer_pool_size=2147483648
      - --innodb_log_buffer_size=268435456
      - --innodb_log_file_size=536870912
      - --innodb-flush-log-at-trx-commit=2
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sql/demo.sql:/docker-entrypoint-initdb.d/1.sql
      - db-data:/var/lib/mysql

  svc_redis:
    env_file: .env
    restart: unless-stopped
    container_name: ${PROJECT}-redis
    image: "bbdrummer/redis-runtime-env:latest"
    volumes:
      - redis-data:/data
