---
version: "3.6"

volumes:
  redis-data:

networks:
  default:
    driver: bridge

services:
  web-php:
    env_file: .env
    restart: unless-stopped
    container_name: ${PROJECT}-web
    image: "bbdrummer/my-application-runtime-php:development"
    ports:
      - "${WEBPORT}:8080"
    volumes:
        - ./:/var/www
        #- ${SRC_PATH}/public/:/var/www/html
    links:
      - svc_db_mysql

  admin-pma:
    env_file: .env
    restart: unless-stopped
    container_name: ${PROJECT}-admin-pma
    image: "phpmyadmin/phpmyadmin"
    environment:
      PMA_HOST: my-application-mysql
    ports:
      - "${PMAPORT}:80"
    links:
      - svc_db_mysql

  svc_db_mysql:
    env_file: .env
    restart: unless-stopped
    container_name: ${PROJECT}-mysql
    command: 'mysqld --authentication_policy=mysql_native_password --user=root'
    image: "bbdrummer/mysql-runtime-env:latest"
    volumes:
      - ./sql/demo.sql:/docker-entrypoint-initdb.d/1.sql
      - ./data:/var/lib/mysql

  svc_redis:
    env_file: .env
    restart: unless-stopped
    container_name: ${PROJECT}-redis
    image: "bbdrummer/redis-runtime-env:latest"
    volumes:
      - redis-data:/data
