tasks:
  - init: |
      source /workspace/my-application/.ops/config/gitpod/env.sh
      composer install --ignore-platform-reqs
      start
    command: |
      source /workspace/my-application/.ops/config/gitpod/env.sh