before_commands:
    - 'apt-get install git git-core'

# language: php
checks:
    php: true
    javascript: true
filter:
    paths:
        - module/Application/src/*
        - module/Admin/src/*
        - module/UIComponents/src/*
    excluded_paths:
        - test/*
        - vendor/*
        - public/*
        - puphpet/*
coding_style:
    php: {  }
build:
    environment:
        variables:
          MYSQL_HOST: '127.0.0.1'
          MYSQL_DATABASE: 'db_myapplication'
          MYSQL_USER: 'root'
          MYSQL_PASS: ''
        php: '8.1'
        mariadb: 10
        memcached: true
        timezone: 'Europe/Berlin'
        hosts:
            myapplication.test: '127.0.0.1'

        apache2:
            modules: ['rewrite']
            sites:
                my-application:
                    web_root: 'public/'
                    host: 'myapplication.test'
    tests:
        before:
            - 'mysql -u root -e "CREATE DATABASE db_myapplication"'
            - 'mysql -u root db_myapplication < sql/install.sql'
            - 'mysql -u root db_myapplication < sql/demo.sql'
        override:
            -
                command: './vendor/bin/phpunit -c ./module/Application/test --coverage-clover=my-application.clover'
                coverage:
                    file: 'my-application.clover'
                    format: 'php-clover'