# admin-pma application
apiVersion: v1
kind: Service
metadata:
  name: PROJECTSLUG-ENVIRONMENT-admin-pma
  namespace: PROJECTNAMESPACE
  labels:
    app: PROJECTSLUG-ENVIRONMENT
    team: PROJECTSLUG-ENVIRONMENT
    stage: ENVIRONMENT
spec:
  type: LoadBalancer
  #type: NodePort
  ports:
    - port: 80
      #targetPort: 80
  selector:
    app: PROJECTSLUG-ENVIRONMENT
    tier: admin
---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: PROJECTSLUG-ENVIRONMENT-admin-pma
  namespace: PROJECTNAMESPACE
  labels:
    app: PROJECTSLUG-ENVIRONMENT
    team: PROJECTSLUG-ENVIRONMENT
    stage: ENVIRONMENT
spec:
  selector:
    matchLabels:
      app: PROJECTSLUG-ENVIRONMENT
      tier: admin
  replicas: 1
  progressDeadlineSeconds: 600
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: PROJECTSLUG-ENVIRONMENT
        team: PROJECTSLUG-ENVIRONMENT
        stage: ENVIRONMENT
        tier: admin
    spec:
      containers:
      - name: PROJECTSLUG-ENVIRONMENT-admin-pma
        image: phpmyadmin/phpmyadmin
        env:
        - name: PMA_ABSOLUTE_URI
          value: "http://PROJECTHOSTNAME/_pma_/"
        - name: PMA_HOST
          value: PROJECTSLUG-ENVIRONMENT-mysql
          #value: PROJECTSLUG-ENVIRONMENT-mysql
        - name: PMA_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 3
          failureThreshold: 5
---
