<?php 
    /** @var \UIComponents\View\Helper\Utilities $oUtilities **/
    $oUtilities = $this->Utilities();
    /** @var \UIComponents\View\Helper\Components $oComponents **/
    $oComponents = $this->Components();
    /** @var \Admin\Entity\User $oUser **/
    $oUser = $this->zfcUserIdentity();
?>
<h4>Element</h4>
<div class="clearfix"><?php
    $body = $oUtilities()->Element(array(
            'tagname'    => 'div',
            'classnames'=> 'callout well',
    ))->setContent('some content...');
    $someContent = $body;
    echo $body->render();
?></div>

<hr />
<h4>Block</h4>
<div class="clearfix"><?php echo ($block = $oUtilities->Block()
    ->setHeader("Here comes the header...")
    ->setFooter("Here comes the footer...")
    ->render()
); ?></div>

<hr />
<h4>Panel</h4>
<div class="clearfix"><?php 

    $body = $oUtilities()->Element(array(
            'tagname'    => 'div',
            'classnames'=> 'panel-body',
    ))->setContent("<em>content, content, content and more...</em>");
    
    $header = $oUtilities()->Element(
        array(
            'tagname'        => 'div',
            'classnames'    => 'panel-heading',
            'content'        => array(
                'tagname'        => 'h3',
                'classnames'    => 'panel-title',
                'content'        => 'the header...'
            )
        )
    );
    $panel = $oUtilities()->Panel()
        ->setHeader( $header
        )
        ->setContent( array(
            array(
                'tagname'        => 'div',
                'classnames'    => 'panel-body',
                'content'        => 'here comes some widget content...'
            ),
            array(
                'tagname'        => 'div',
                'classnames'    => 'panel-body',
                'content'        => array(
                    '<p>here comes other content...</p>',
                    '<p>here comes other content...</p>',
                    '<p>',
                        '<a id="xhrtest" ' .
                            'class="btn-cta-xhr cta-xhr-modal" ' .
                            'href="' . $this->url('application/default', array(
                                'controller' => 'index',
                                'action' => 'xhrtest'
                            )) . '"' .
                        '>',
                            'AJAX/XMLHTTPRequest test request',
                        '</a>',
                    '</p>',
                    $someContent
                )
            ),
            $body
        ) )
        ->setFooter( array(
            'tagname'        => 'div',
            'classnames'    => 'panel-footer',
            'content'        => 'footer content here...'
        ) )
    ;
    
     $panel->setTagname('section');
    echo $panel->render();
    
?></div>
