<?php 
/** @var \UIComponents\View\Helper\Utilities $oUtilities **/
$oUtilities = $this->Utilities();
/** @var \UIComponents\View\Helper\Components $oComponents **/
$oComponents = $this->Components();
/** @var \Admin\Entity\User $oUser **/
$oUser = $this->zfcUserIdentity();

$messages = $this->flashMessenger()
    ->renderCurrent('error', array('error panel panel-body panel-error'));
$messages .= $this->flashMessenger()
    ->renderCurrents('warning', array('warning panel panel-body panel-warning'));
$messages .= $this->flashMessenger()
    ->renderCurrents('success', array('success panel panel-body panel-success'));
$messages .= $this->flashMessenger()
    ->renderCurrents('info', array('info panel panel-body panel-info'));
$this->flashMessenger()->getPluginFlashMessenger()->clearCurrentMessagesFromContainer();

$modalLayout = $oComponents->Modal()
    ->setHeader( (isset($this->title) ? $this->title : "") )
    ->setAttribute('data-test', 'modal-'. $oUtilities->requestSlug())
    ->setContent(
        array(
            'tagname' => 'div',
            'classnames' => 'modal-body panel-wrap panel-' . $oUtilities->requestSlug(),
            'content' => $messages . $this->content,
            'attr' => [
                'data-test' => 'modal-body'
            ]
        )
    )
;

echo $modalLayout . $this->inlineScript();
