---
- name: 'Setup project'
  hosts: localhost
  connection: local
  tasks:
    # Create user generated folder
    - name: Create generated folder
      file: path=../generated/setup state=directory mode=0755

    # Create temp files
    - name: Create project yaml temp file
      tempfile:
        state: file
        suffix: temp
      register: tempfile_1

    # Project info
    - name: Project info
      shell: echo "{{ project }} / {{ namespace }} = {{ app_env }}, {{ release }}, {{ teamlabel }}"
      delegate_to: localhost

    # Generate yaml files
    - name: Generate project yaml file
      template:
        src: "cronjob.yml.j2"
        dest: "{{ tempfile_1.path }}"
        mode: '0644'

    # Save yaml file
    - name: Save backend deployment yaml file
      copy:
        src: "{{ tempfile_1.path }}"
        dest: '../generated/setup/cronjob.yml'
        mode: '0755'
      delegate_to: localhost
      when: tempfile_1.path is defined

    # Enable cronjob
    - name: Setup cronjob in namespace
      shell: kubectl apply -f {{ tempfile_1.path }} -n {{ namespace }}
      delegate_to: localhost
      when: tempfile_1.path is defined and cronjob_enable is defined 

    # Disable cronjob
    - name: Remove cronjob from namespace
      shell: kubectl delete -f {{ tempfile_1.path }} -n {{ namespace }} --ignore-not-found
      delegate_to: localhost
      when: tempfile_1.path is defined and cronjob_disable is defined 

    # Delete temp files
    - name: Delete project yaml temp file
      file:
        path: "{{ tempfile_1.path }}"
        state: absent
      when: tempfile_1.path is defined
